name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Ruby (2.6)
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.6'
        bundler-cache: true
    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec